In [1]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from datetime import date, datetime
import pytz

In [2]:
seoul_tz = pytz.timezone("Asia/Seoul")
today = datetime.now(seoul_tz).strftime("%Y-%m-%d")
today
# CSV 파일 읽기
df = pd.read_csv(f"/Users/kjb/Desktop/hateslop/프로젝트/테스트데이터/({today})테스트.csv")
df

,RSI,BB_Dist,MACD_6_13_4,MACDh_6_13_4,MACDs_6_13_4,STOCHk_5_3_1,STOCHd_5_3_1,OBV,ATR,Golden_Cross,ADX,CCI,ROC,CMF,ADL
0,34.818257,2.971671,0.404422,-0.544812,0.949234,38.604518,54.850222,27288100.0,3.437460,0.0,19.632496,-10.252532,-3.914169,0.185646,2.483952e+06
1,22.618379,2.107095,-1.273435,-0.367314,-0.906120,6.291348,14.086580,-11126400.0,1.693545,0.0,22.282688,-189.725322,-10.649459,-0.037209,-1.638624e+06
2,59.053730,3.229031,0.298189,0.058526,0.239663,79.856194,78.653118,54008700.0,2.491807,0.0,12.626219,18.025628,-0.912460,0.115392,1.597704e+07
3,62.878301,6.011547,0.379580,0.380555,-0.000976,100.000000,89.963887,63501700.0,4.838278,0.0,22.379516,10.536966,1.613956,0.156655,6.249187e+07
4,43.222485,2.118973,0.760503,-0.439483,1.199986,41.902446,69.830253,9262100.0,6.159647,0.0,26.591492,-19.667762,-1.013567,0.197836,1.742308e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,53.637635,3.480112,0.590916,-0.125604,0.716520,64.488094,71.578459,12851100.0,2.210804,1.0,42.712559,11.477851,-1.506337,-0.070582,2.742509e+06
499,48.239121,2.359810,-0.617710,0.036042,-0.653752,73.639062,55.718118,-3898500.0,2.502425,0.0,13.413975,-93.038280,-1.844086,0.045074,5.952105e+06
500,39.597386,9.774693,2.050740,-1.399414,3.450153,26.234912,54.240411,5900100.0,8.886091,0.0,41.066927,4.331550,-4.876590,0.267951,4.677895e+06
501,31.653815,1.642634,-1.177407,-0.052963,-1.124444,12.623812,42.571284,12017200.0,2.513008,0.0,31.845654,-116.358957,-6.023720,-0.067989,1.409002e+06
502,79.134568,10.536359,2.553818,0.246656,2.307162,93.792019,91.265338,40542100.0,3.950909,0.0,10.765018,139.918610,3.913153,0.187221,1.960186e+07

In [3]:
features = [
    'RSI', 'BB_Dist', 'MACD_6_13_4', 'MACDh_6_13_4', 'MACDs_6_13_4',
    'STOCHk_5_3_1', 'STOCHd_5_3_1', 'OBV','ATR',
    'Golden_Cross','ADX', 'CCI', 'ROC', 'CMF','ADL'
]

test = df[features]
test

,RSI,BB_Dist,MACD_6_13_4,MACDh_6_13_4,MACDs_6_13_4,STOCHk_5_3_1,STOCHd_5_3_1,OBV,ATR,Golden_Cross,ADX,CCI,ROC,CMF,ADL
0,34.818257,2.971671,0.404422,-0.544812,0.949234,38.604518,54.850222,27288100.0,3.437460,0.0,19.632496,-10.252532,-3.914169,0.185646,2.483952e+06
1,22.618379,2.107095,-1.273435,-0.367314,-0.906120,6.291348,14.086580,-11126400.0,1.693545,0.0,22.282688,-189.725322,-10.649459,-0.037209,-1.638624e+06
2,59.053730,3.229031,0.298189,0.058526,0.239663,79.856194,78.653118,54008700.0,2.491807,0.0,12.626219,18.025628,-0.912460,0.115392,1.597704e+07
3,62.878301,6.011547,0.379580,0.380555,-0.000976,100.000000,89.963887,63501700.0,4.838278,0.0,22.379516,10.536966,1.613956,0.156655,6.249187e+07
4,43.222485,2.118973,0.760503,-0.439483,1.199986,41.902446,69.830253,9262100.0,6.159647,0.0,26.591492,-19.667762,-1.013567,0.197836,1.742308e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,53.637635,3.480112,0.590916,-0.125604,0.716520,64.488094,71.578459,12851100.0,2.210804,1.0,42.712559,11.477851,-1.506337,-0.070582,2.742509e+06
499,48.239121,2.359810,-0.617710,0.036042,-0.653752,73.639062,55.718118,-3898500.0,2.502425,0.0,13.413975,-93.038280,-1.844086,0.045074,5.952105e+06
500,39.597386,9.774693,2.050740,-1.399414,3.450153,26.234912,54.240411,5900100.0,8.886091,0.0,41.066927,4.331550,-4.876590,0.267951,4.677895e+06
501,31.653815,1.642634,-1.177407,-0.052963,-1.124444,12.623812,42.571284,12017200.0,2.513008,0.0,31.845654,-116.358957,-6.023720,-0.067989,1.409002e+06
502,79.134568,10.536359,2.553818,0.246656,2.307162,93.792019,91.265338,40542100.0,3.950909,0.0,10.765018,139.918610,3.913153,0.187221,1.960186e+07

In [4]:
from xgboost import XGBClassifier

# 모델 로드
model = XGBClassifier()
model.load_model("/Users/kjb/Desktop/hateslop/프로젝트/예측모델/xgb_model.json")

# 예측 사용 가능
y_pred = model.predict(test)
y_proba = model.predict_proba(test)

In [5]:
import pandas as pd

# 위키피디아의 S&P 500 구성 종목 목록 URL
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

# HTML 테이블을 읽어오기
tables = pd.read_html(url)
df = tables[0]  # 첫 번째 테이블이 S&P 500 구성 종목 목록


# 티커와 기업명 추출
ticker_Group= df['Symbol'].tolist()
company_names = df['Security'].tolist()

ticker_Group = [t.replace(".", "-") for t in ticker_Group]
company_names = [t.replace(".", "-") for t in company_names]
ticker_names = dict(zip(ticker_Group, company_names))

ticker_Group
ticker_names
for i, ticker in enumerate(ticker_Group):
    kor_name = ticker_names.get(ticker, ticker)
    prob = y_proba[i][1] * 100
    direction = "상승" if prob >= 50 else "하락"
    print(f"{kor_name} 상승확률 : {prob:.2f}%, {kor_name} 상승여부 : {direction}")

3M 상승확률 : 99.83%, 3M 상승여부 : 상승
A- O- Smith 상승확률 : 99.84%, A- O- Smith 상승여부 : 상승
Abbott Laboratories 상승확률 : 63.40%, Abbott Laboratories 상승여부 : 상승
AbbVie 상승확률 : 0.36%, AbbVie 상승여부 : 하락
Accenture 상승확률 : 1.00%, Accenture 상승여부 : 하락
Adobe Inc- 상승확률 : 99.72%, Adobe Inc- 상승여부 : 상승
Advanced Micro Devices 상승확률 : 99.51%, Advanced Micro Devices 상승여부 : 상승
AES Corporation 상승확률 : 97.39%, AES Corporation 상승여부 : 상승
Aflac 상승확률 : 51.59%, Aflac 상승여부 : 상승
Agilent Technologies 상승확률 : 66.53%, Agilent Technologies 상승여부 : 상승
Air Products 상승확률 : 98.68%, Air Products 상승여부 : 상승
Airbnb 상승확률 : 99.53%, Airbnb 상승여부 : 상승
Akamai Technologies 상승확률 : 99.66%, Akamai Technologies 상승여부 : 상승
Albemarle Corporation 상승확률 : 100.00%, Albemarle Corporation 상승여부 : 상승
Alexandria Real Estate Equities 상승확률 : 71.68%, Alexandria Real Estate Equities 상승여부 : 상승
Align Technology 상승확률 : 74.22%, Align Technology 상승여부 : 상승
Allegion 상승확률 : 2.93%, Allegion 상승여부 : 하락
Alliant Energy 상승확률 : 66.77%, Alliant Energy 상승여부 : 상승
Allstate 상승확률 : 2.42%, Allstate 상승여부 : 하락
Alphabet Inc- (Class A) 상승확률 : 0.03%, Alphabet Inc- (Class A) 상승여부 : 하락
Alphabet Inc- (Class C) 상승확률 : 0.33%, Alphabet Inc- (Class C) 상승여부 : 하락
Altria 상승확률 : 0.01%, Altria 상승여부 : 하락
Amazon 상승확률 : 7.21%, Amazon 상승여부 : 하락
Amcor 상승확률 : 96.68%, Amcor 상승여부 : 상승
Ameren 상승확률 : 76.54%, Ameren 상승여부 : 상승
American Electric Power 상승확률 : 0.03%, American Electric Power 상승여부 : 하락
American Express 상승확률 : 99.27%, American Express 상승여부 : 상승
American International Group 상승확률 : 25.24%, American International Group 상승여부 : 하락
American Tower 상승확률 : 0.02%, American Tower 상승여부 : 하락
American Water Works 상승확률 : 0.01%, American Water Works 상승여부 : 하락
Ameriprise Financial 상승확률 : 90.48%, Ameriprise Financial 상승여부 : 상승
Ametek 상승확률 : 77.74%, Ametek 상승여부 : 상승
Amgen 상승확률 : 54.49%, Amgen 상승여부 : 상승
Amphenol 상승확률 : 99.62%, Amphenol 상승여부 : 상승
Analog Devices 상승확률 : 99.07%, Analog Devices 상승여부 : 상승
Ansys 상승확률 : 96.44%, Ansys 상승여부 : 상승
Aon plc 상승확률 : 3.63%, Aon plc 상승여부 : 하락
APA Corporation 상승확률 : 99.96%, APA Corporation 상승여부 : 상승
Apollo Global Management 상승확률 : 83.60%, Apollo Global Management 상승여부 : 상승
Apple Inc- 상승확률 : 48.92%, Apple Inc- 상승여부 : 하락
Applied Materials 상승확률 : 99.98%, Applied Materials 상승여부 : 상승
Aptiv 상승확률 : 99.95%, Aptiv 상승여부 : 상승
Arch Capital Group 상승확률 : 12.66%, Arch Capital Group 상승여부 : 하락
Archer Daniels Midland 상승확률 : 0.00%, Archer Daniels Midland 상승여부 : 하락
Arista Networks 상승확률 : 99.75%, Arista Networks 상승여부 : 상승
Arthur J- Gallagher & Co- 상승확률 : 0.01%, Arthur J- Gallagher & Co- 상승여부 : 하락
Assurant 상승확률 : 91.08%, Assurant 상승여부 : 상승
AT&T 상승확률 : 4.38%, AT&T 상승여부 : 하락
Atmos Energy 상승확률 : 62.63%, Atmos Energy 상승여부 : 상승
Autodesk 상승확률 : 98.14%, Autodesk 상승여부 : 상승
Automatic Data Processing 상승확률 : 69.61%, Automatic Data Processing 상승여부 : 상승
AutoZone 상승확률 : 16.67%, AutoZone 상승여부 : 하락
AvalonBay Communities 상승확률 : 0.02%, AvalonBay Communities 상승여부 : 하락
Avery Dennison 상승확률 : 99.99%, Avery Dennison 상승여부 : 상승
Axon Enterprise 상승확률 : 25.94%, Axon Enterprise 상승여부 : 하락
Baker Hughes 상승확률 : 40.65%, Baker Hughes 상승여부 : 하락
Ball Corporation 상승확률 : 99.82%, Ball Corporation 상승여부 : 상승
Bank of America 상승확률 : 99.68%, Bank of America 상승여부 : 상승
Baxter International 상승확률 : 98.41%, Baxter International 상승여부 : 상승
Becton Dickinson 상승확률 : 98.34%, Becton Dickinson 상승여부 : 상승
Berkshire Hathaway 상승확률 : 0.00%, Berkshire Hathaway 상승여부 : 하락
Best Buy 상승확률 : 67.19%, Best Buy 상승여부 : 상승
Bio-Techne 상승확률 : 29.77%, Bio-Techne 상승여부 : 하락
Biogen 상승확률 : 52.98%, Biogen 상승여부 : 상승
BlackRock 상승확률 : 98.89%, BlackRock 상승여부 : 상승
Blackstone Inc- 상승확률 : 59.52%, Blackstone Inc- 상승여부 : 상승
BNY Mellon 상승확률 : 84.02%, BNY Mellon 상승여부 : 상승
Boeing 상승확률 : 99.99%, Boeing 상승여부 : 상승
Booking Holdings 상승확률 : 10.86%, Booking Holdings 상승여부 : 하락
Boston Scientific 상승확률 : 0.00%, Boston Scientific 상승여부 : 하락
Bristol Myers Squibb 상승확률 : 0.00%, Bristol Myers Squibb 상승여부 : 하락
Broadcom 상승확률 : 99.72%, Broadcom 상승여부 : 상승
Broadridge Financial Solutions 상승확률 : 99.71%, Broadridge Financial Solutions 상승여부 : 상승
Brown & Brown 상승확률 : 0.00%, Brown & Brown 상승여부 : 하락
Brown–Forman 상승확률 : 88.04%, Brown–Forman 상승여부 : 상승
Builders FirstSource 상승확률 : 99.95%, Builders FirstSource 상승여부 : 상승
Bunge Global 상승확률 : 0.00%, Bunge Global 상승여부 : 하락
BXP, Inc- 상승확률 : 100.00%, BXP, Inc- 상승여부 : 상승
C-H- Robinson 상승확률 : 76.56%, C-H- Robinson 상승여부 : 상승
Cadence Design Systems 상승확률 : 86.73%, Cadence Design Systems 상승여부 : 상승
Caesars Entertainment 상승확률 : 28.46%, Caesars Entertainment 상승여부 : 하락
Camden Property Trust 상승확률 : 87.35%, Camden Property Trust 상승여부 : 상승
Campbell's Company (The) 상승확률 : 64.17%, Campbell's Company (The) 상승여부 : 상승
Capital One 상승확률 : 97.76%, Capital One 상승여부 : 상승
Cardinal Health 상승확률 : 4.13%, Cardinal Health 상승여부 : 하락
CarMax 상승확률 : 98.00%, CarMax 상승여부 : 상승
Carnival 상승확률 : 99.98%, Carnival 상승여부 : 상승
Carrier Global 상승확률 : 99.02%, Carrier Global 상승여부 : 상승
Caterpillar Inc- 상승확률 : 91.74%, Caterpillar Inc- 상승여부 : 상승
Cboe Global Markets 상승확률 : 0.04%, Cboe Global Markets 상승여부 : 하락
CBRE Group 상승확률 : 90.04%, CBRE Group 상승여부 : 상승
CDW Corporation 상승확률 : 99.97%, CDW Corporation 상승여부 : 상승
Cencora 상승확률 : 0.12%, Cencora 상승여부 : 하락
Centene Corporation 상승확률 : 99.93%, Centene Corporation 상승여부 : 상승
CenterPoint Energy 상승확률 : 4.65%, CenterPoint Energy 상승여부 : 하락
CF Industries 상승확률 : 1.07%, CF Industries 상승여부 : 하락
Charles River Laboratories 상승확률 : 99.70%, Charles River Laboratories 상승여부 : 상승
Charles Schwab Corporation 상승확률 : 55.33%, Charles Schwab Corporation 상승여부 : 상승
Charter Communications 상승확률 : 0.89%, Charter Communications 상승여부 : 하락
Chevron Corporation 상승확률 : 96.47%, Chevron Corporation 상승여부 : 상승
Chipotle Mexican Grill 상승확률 : 98.59%, Chipotle Mexican Grill 상승여부 : 상승
Chubb Limited 상승확률 : 0.01%, Chubb Limited 상승여부 : 하락
Church & Dwight 상승확률 : 55.32%, Church & Dwight 상승여부 : 상승
Cigna 상승확률 : 2.19%, Cigna 상승여부 : 하락
Cincinnati Financial 상승확률 : 13.54%, Cincinnati Financial 상승여부 : 하락
Cintas 상승확률 : 95.49%, Cintas 상승여부 : 상승
Cisco 상승확률 : 96.13%, Cisco 상승여부 : 상승
Citigroup 상승확률 : 99.95%, Citigroup 상승여부 : 상승
Citizens Financial Group 상승확률 : 99.71%, Citizens Financial Group 상승여부 : 상승
Clorox 상승확률 : 60.62%, Clorox 상승여부 : 상승
CME Group 상승확률 : 0.00%, CME Group 상승여부 : 하락
CMS Energy 상승확률 : 89.29%, CMS Energy 상승여부 : 상승
Coca-Cola Company (The) 상승확률 : 0.00%, Coca-Cola Company (The) 상승여부 : 하락
Cognizant 상승확률 : 94.17%, Cognizant 상승여부 : 상승
Coinbase 상승확률 : 99.28%, Coinbase 상승여부 : 상승
Colgate-Palmolive 상승확률 : 0.00%, Colgate-Palmolive 상승여부 : 하락
Comcast 상승확률 : 99.36%, Comcast 상승여부 : 상승
Conagra Brands 상승확률 : 16.92%, Conagra Brands 상승여부 : 하락
ConocoPhillips 상승확률 : 84.02%, ConocoPhillips 상승여부 : 상승
Consolidated Edison 상승확률 : 2.96%, Consolidated Edison 상승여부 : 하락
Constellation Brands 상승확률 : 99.82%, Constellation Brands 상승여부 : 상승
Constellation Energy 상승확률 : 95.03%, Constellation Energy 상승여부 : 상승
Cooper Companies (The) 상승확률 : 99.04%, Cooper Companies (The) 상승여부 : 상승
Copart 상승확률 : 98.16%, Copart 상승여부 : 상승
Corning Inc- 상승확률 : 99.77%, Corning Inc- 상승여부 : 상승
Corpay 상승확률 : 99.85%, Corpay 상승여부 : 상승
Corteva 상승확률 : 64.34%, Corteva 상승여부 : 상승
CoStar Group 상승확률 : 100.00%, CoStar Group 상승여부 : 상승
Costco 상승확률 : 91.33%, Costco 상승여부 : 상승
Coterra 상승확률 : 99.22%, Coterra 상승여부 : 상승
CrowdStrike 상승확률 : 99.83%, CrowdStrike 상승여부 : 상승
Crown Castle 상승확률 : 60.49%, Crown Castle 상승여부 : 상승
CSX Corporation 상승확률 : 99.91%, CSX Corporation 상승여부 : 상승
Cummins 상승확률 : 100.00%, Cummins 상승여부 : 상승
CVS Health 상승확률 : 4.64%, CVS Health 상승여부 : 하락
Danaher Corporation 상승확률 : 96.80%, Danaher Corporation 상승여부 : 상승
Darden Restaurants 상승확률 : 99.79%, Darden Restaurants 상승여부 : 상승
DaVita 상승확률 : 99.97%, DaVita 상승여부 : 상승
Dayforce 상승확률 : 94.57%, Dayforce 상승여부 : 상승
Deckers Brands 상승확률 : 68.48%, Deckers Brands 상승여부 : 상승
Deere & Company 상승확률 : 98.74%, Deere & Company 상승여부 : 상승
Dell Technologies 상승확률 : 99.99%, Dell Technologies 상승여부 : 상승
Delta Air Lines 상승확률 : 96.62%, Delta Air Lines 상승여부 : 상승
Devon Energy 상승확률 : 94.13%, Devon Energy 상승여부 : 상승
Dexcom 상승확률 : 98.60%, Dexcom 상승여부 : 상승
Diamondback Energy 상승확률 : 98.52%, Diamondback Energy 상승여부 : 상승
Digital Realty 상승확률 : 96.64%, Digital Realty 상승여부 : 상승
Dollar General 상승확률 : 100.00%, Dollar General 상승여부 : 상승
Dollar Tree 상승확률 : 99.99%, Dollar Tree 상승여부 : 상승
Dominion Energy 상승확률 : 65.96%, Dominion Energy 상승여부 : 상승
Domino's 상승확률 : 48.01%, Domino's 상승여부 : 하락
DoorDash 상승확률 : 77.86%, DoorDash 상승여부 : 상승
Dover Corporation 상승확률 : 99.95%, Dover Corporation 상승여부 : 상승
Dow Inc- 상승확률 : 99.25%, Dow Inc- 상승여부 : 상승
D- R- Horton 상승확률 : 98.34%, D- R- Horton 상승여부 : 상승
DTE Energy 상승확률 : 35.31%, DTE Energy 상승여부 : 하락
Duke Energy 상승확률 : 0.01%, Duke Energy 상승여부 : 하락
DuPont 상승확률 : 73.83%, DuPont 상승여부 : 상승
Eastman Chemical Company 상승확률 : 99.68%, Eastman Chemical Company 상승여부 : 상승
Eaton Corporation 상승확률 : 99.95%, Eaton Corporation 상승여부 : 상승
eBay Inc- 상승확률 : 99.68%, eBay Inc- 상승여부 : 상승
Ecolab 상승확률 : 30.96%, Ecolab 상승여부 : 하락
Edison International 상승확률 : 99.69%, Edison International 상승여부 : 상승
Edwards Lifesciences 상승확률 : 1.03%, Edwards Lifesciences 상승여부 : 하락
Electronic Arts 상승확률 : 79.96%, Electronic Arts 상승여부 : 상승
Elevance Health 상승확률 : 70.88%, Elevance Health 상승여부 : 상승
Emerson Electric 상승확률 : 99.99%, Emerson Electric 상승여부 : 상승
Enphase Energy 상승확률 : 96.29%, Enphase Energy 상승여부 : 상승
Entergy 상승확률 : 6.32%, Entergy 상승여부 : 하락
EOG Resources 상승확률 : 10.99%, EOG Resources 상승여부 : 하락
EPAM Systems 상승확률 : 99.94%, EPAM Systems 상승여부 : 상승
EQT Corporation 상승확률 : 26.66%, EQT Corporation 상승여부 : 하락
Equifax 상승확률 : 99.55%, Equifax 상승여부 : 상승
Equinix 상승확률 : 88.68%, Equinix 상승여부 : 상승
Equity Residential 상승확률 : 0.04%, Equity Residential 상승여부 : 하락
Erie Indemnity 상승확률 : 75.46%, Erie Indemnity 상승여부 : 상승
Essex Property Trust 상승확률 : 0.71%, Essex Property Trust 상승여부 : 하락
Estée Lauder Companies (The) 상승확률 : 95.12%, Estée Lauder Companies (The) 상승여부 : 상승
Everest Group 상승확률 : 47.19%, Everest Group 상승여부 : 하락
Evergy 상승확률 : 0.00%, Evergy 상승여부 : 하락
Eversource Energy 상승확률 : 81.14%, Eversource Energy 상승여부 : 상승
Exelon 상승확률 : 0.05%, Exelon 상승여부 : 하락
Expand Energy 상승확률 : 1.23%, Expand Energy 상승여부 : 하락
Expedia Group 상승확률 : 79.15%, Expedia Group 상승여부 : 상승
Expeditors International 상승확률 : 98.71%, Expeditors International 상승여부 : 상승
Extra Space Storage 상승확률 : 0.01%, Extra Space Storage 상승여부 : 하락
ExxonMobil 상승확률 : 66.10%, ExxonMobil 상승여부 : 상승
F5, Inc- 상승확률 : 73.25%, F5, Inc- 상승여부 : 상승
FactSet 상승확률 : 0.00%, FactSet 상승여부 : 하락
Fair Isaac 상승확률 : 32.08%, Fair Isaac 상승여부 : 하락
Fastenal 상승확률 : 98.00%, Fastenal 상승여부 : 상승
Federal Realty Investment Trust 상승확률 : 92.33%, Federal Realty Investment Trust 상승여부 : 상승
FedEx 상승확률 : 45.17%, FedEx 상승여부 : 하락
Fidelity National Information Services 상승확률 : 98.73%, Fidelity National Information Services 상승여부 : 상승
Fifth Third Bancorp 상승확률 : 99.35%, Fifth Third Bancorp 상승여부 : 상승
First Solar 상승확률 : 99.98%, First Solar 상승여부 : 상승
FirstEnergy 상승확률 : 0.04%, FirstEnergy 상승여부 : 하락
Fiserv 상승확률 : 42.31%, Fiserv 상승여부 : 하락
Ford Motor Company 상승확률 : 93.16%, Ford Motor Company 상승여부 : 상승
Fortinet 상승확률 : 1.29%, Fortinet 상승여부 : 하락
Fortive 상승확률 : 99.99%, Fortive 상승여부 : 상승
Fox Corporation (Class A) 상승확률 : 87.14%, Fox Corporation (Class A) 상승여부 : 상승
Fox Corporation (Class B) 상승확률 : 89.26%, Fox Corporation (Class B) 상승여부 : 상승
Franklin Resources 상승확률 : 97.33%, Franklin Resources 상승여부 : 상승
Freeport-McMoRan 상승확률 : 87.86%, Freeport-McMoRan 상승여부 : 상승
Garmin 상승확률 : 98.61%, Garmin 상승여부 : 상승
Gartner 상승확률 : 98.30%, Gartner 상승여부 : 상승
GE Aerospace 상승확률 : 98.66%, GE Aerospace 상승여부 : 상승
GE HealthCare 상승확률 : 99.10%, GE HealthCare 상승여부 : 상승
GE Vernova 상승확률 : 72.66%, GE Vernova 상승여부 : 상승
Gen Digital 상승확률 : 99.84%, Gen Digital 상승여부 : 상승
Generac 상승확률 : 100.00%, Generac 상승여부 : 상승
General Dynamics 상승확률 : 72.17%, General Dynamics 상승여부 : 상승
General Mills 상승확률 : 91.08%, General Mills 상승여부 : 상승
General Motors 상승확률 : 98.37%, General Motors 상승여부 : 상승
Genuine Parts Company 상승확률 : 2.41%, Genuine Parts Company 상승여부 : 하락
Gilead Sciences 상승확률 : 10.54%, Gilead Sciences 상승여부 : 하락
Global Payments 상승확률 : 97.38%, Global Payments 상승여부 : 상승
Globe Life 상승확률 : 32.41%, Globe Life 상승여부 : 하락
GoDaddy 상승확률 : 99.51%, GoDaddy 상승여부 : 상승
Goldman Sachs 상승확률 : 89.07%, Goldman Sachs 상승여부 : 상승
Halliburton 상승확률 : 99.49%, Halliburton 상승여부 : 상승
Hartford (The) 상승확률 : 61.17%, Hartford (The) 상승여부 : 상승
Hasbro 상승확률 : 7.08%, Hasbro 상승여부 : 하락
HCA Healthcare 상승확률 : 94.92%, HCA Healthcare 상승여부 : 상승
Healthpeak Properties 상승확률 : 16.82%, Healthpeak Properties 상승여부 : 하락
Henry Schein 상승확률 : 99.83%, Henry Schein 상승여부 : 상승
Hershey Company (The) 상승확률 : 98.34%, Hershey Company (The) 상승여부 : 상승
Hess Corporation 상승확률 : 99.91%, Hess Corporation 상승여부 : 상승
Hewlett Packard Enterprise 상승확률 : 99.81%, Hewlett Packard Enterprise 상승여부 : 상승
Hilton Worldwide 상승확률 : 99.87%, Hilton Worldwide 상승여부 : 상승
Hologic 상승확률 : 95.24%, Hologic 상승여부 : 상승
Home Depot (The) 상승확률 : 99.92%, Home Depot (The) 상승여부 : 상승
Honeywell 상승확률 : 86.53%, Honeywell 상승여부 : 상승
Hormel Foods 상승확률 : 17.67%, Hormel Foods 상승여부 : 하락
Host Hotels & Resorts 상승확률 : 99.92%, Host Hotels & Resorts 상승여부 : 상승
Howmet Aerospace 상승확률 : 7.13%, Howmet Aerospace 상승여부 : 하락
HP Inc- 상승확률 : 56.66%, HP Inc- 상승여부 : 상승
Hubbell Incorporated 상승확률 : 99.08%, Hubbell Incorporated 상승여부 : 상승
Humana 상승확률 : 99.52%, Humana 상승여부 : 상승
Huntington Bancshares 상승확률 : 99.08%, Huntington Bancshares 상승여부 : 상승
Huntington Ingalls Industries 상승확률 : 99.99%, Huntington Ingalls Industries 상승여부 : 상승
IBM 상승확률 : 83.47%, IBM 상승여부 : 상승
IDEX Corporation 상승확률 : 99.38%, IDEX Corporation 상승여부 : 상승
Idexx Laboratories 상승확률 : 99.97%, Idexx Laboratories 상승여부 : 상승
Illinois Tool Works 상승확률 : 99.98%, Illinois Tool Works 상승여부 : 상승
Incyte 상승확률 : 99.73%, Incyte 상승여부 : 상승
Ingersoll Rand 상승확률 : 98.99%, Ingersoll Rand 상승여부 : 상승
Insulet Corporation 상승확률 : 2.36%, Insulet Corporation 상승여부 : 하락
Intel 상승확률 : 99.86%, Intel 상승여부 : 상승
Intercontinental Exchange 상승확률 : 28.18%, Intercontinental Exchange 상승여부 : 하락
International Flavors & Fragrances 상승확률 : 99.85%, International Flavors & Fragrances 상승여부 : 상승
International Paper 상승확률 : 95.49%, International Paper 상승여부 : 상승
Interpublic Group of Companies (The) 상승확률 : 99.95%, Interpublic Group of Companies (The) 상승여부 : 상승
Intuit 상승확률 : 59.20%, Intuit 상승여부 : 상승
Intuitive Surgical 상승확률 : 88.83%, Intuitive Surgical 상승여부 : 상승
Invesco 상승확률 : 38.45%, Invesco 상승여부 : 하락
Invitation Homes 상승확률 : 0.05%, Invitation Homes 상승여부 : 하락
IQVIA 상승확률 : 98.77%, IQVIA 상승여부 : 상승
Iron Mountain 상승확률 : 94.73%, Iron Mountain 상승여부 : 상승
J-B- Hunt 상승확률 : 99.59%, J-B- Hunt 상승여부 : 상승
Jabil 상승확률 : 99.91%, Jabil 상승여부 : 상승
Jack Henry & Associates 상승확률 : 44.81%, Jack Henry & Associates 상승여부 : 하락
Jacobs Solutions 상승확률 : 98.80%, Jacobs Solutions 상승여부 : 상승
Johnson & Johnson 상승확률 : 0.24%, Johnson & Johnson 상승여부 : 하락
Johnson Controls 상승확률 : 98.82%, Johnson Controls 상승여부 : 상승
JPMorgan Chase 상승확률 : 99.89%, JPMorgan Chase 상승여부 : 상승
Juniper Networks 상승확률 : 62.32%, Juniper Networks 상승여부 : 상승
Kellanova 상승확률 : 0.00%, Kellanova 상승여부 : 하락
Kenvue 상승확률 : 0.00%, Kenvue 상승여부 : 하락
Keurig Dr Pepper 상승확률 : 0.11%, Keurig Dr Pepper 상승여부 : 하락
KeyCorp 상승확률 : 99.43%, KeyCorp 상승여부 : 상승
Keysight Technologies 상승확률 : 96.42%, Keysight Technologies 상승여부 : 상승
Kimberly-Clark 상승확률 : 0.00%, Kimberly-Clark 상승여부 : 하락
Kimco Realty 상승확률 : 99.85%, Kimco Realty 상승여부 : 상승
Kinder Morgan 상승확률 : 35.55%, Kinder Morgan 상승여부 : 하락
KKR & Co- 상승확률 : 48.66%, KKR & Co- 상승여부 : 하락
KLA Corporation 상승확률 : 99.70%, KLA Corporation 상승여부 : 상승
Kraft Heinz 상승확률 : 84.77%, Kraft Heinz 상승여부 : 상승
Kroger 상승확률 : 0.00%, Kroger 상승여부 : 하락
L3Harris 상승확률 : 77.74%, L3Harris 상승여부 : 상승
Labcorp 상승확률 : 98.70%, Labcorp 상승여부 : 상승
Lam Research 상승확률 : 90.98%, Lam Research 상승여부 : 상승
Lamb Weston 상승확률 : 88.22%, Lamb Weston 상승여부 : 상승
Las Vegas Sands 상승확률 : 99.64%, Las Vegas Sands 상승여부 : 상승
Leidos 상승확률 : 99.13%, Leidos 상승여부 : 상승
Lennar 상승확률 : 98.74%, Lennar 상승여부 : 상승
Lennox International 상승확률 : 99.99%, Lennox International 상승여부 : 상승
Lilly (Eli) 상승확률 : 3.39%, Lilly (Eli) 상승여부 : 하락
Linde plc 상승확률 : 96.69%, Linde plc 상승여부 : 상승
Live Nation Entertainment 상승확률 : 2.34%, Live Nation Entertainment 상승여부 : 하락
LKQ Corporation 상승확률 : 98.18%, LKQ Corporation 상승여부 : 상승
Lockheed Martin 상승확률 : 0.59%, Lockheed Martin 상승여부 : 하락
Loews Corporation 상승확률 : 19.09%, Loews Corporation 상승여부 : 하락
Lowe's 상승확률 : 98.39%, Lowe's 상승여부 : 상승
Lululemon Athletica 상승확률 : 99.96%, Lululemon Athletica 상승여부 : 상승
LyondellBasell 상승확률 : 99.99%, LyondellBasell 상승여부 : 상승
M&T Bank 상승확률 : 99.98%, M&T Bank 상승여부 : 상승
Marathon Petroleum 상승확률 : 99.07%, Marathon Petroleum 상승여부 : 상승
MarketAxess 상승확률 : 0.00%, MarketAxess 상승여부 : 하락
Marriott International 상승확률 : 100.00%, Marriott International 상승여부 : 상승
Marsh McLennan 상승확률 : 0.21%, Marsh McLennan 상승여부 : 하락
Martin Marietta Materials 상승확률 : 99.48%, Martin Marietta Materials 상승여부 : 상승
Masco 상승확률 : 99.64%, Masco 상승여부 : 상승
Mastercard 상승확률 : 96.89%, Mastercard 상승여부 : 상승
Match Group 상승확률 : 92.09%, Match Group 상승여부 : 상승
McCormick & Company 상승확률 : 2.67%, McCormick & Company 상승여부 : 하락
McDonald's 상승확률 : 30.52%, McDonald's 상승여부 : 하락
McKesson Corporation 상승확률 : 0.00%, McKesson Corporation 상승여부 : 하락
Medtronic 상승확률 : 99.63%, Medtronic 상승여부 : 상승
Merck & Co- 상승확률 : 53.15%, Merck & Co- 상승여부 : 상승
Meta Platforms 상승확률 : 9.11%, Meta Platforms 상승여부 : 하락
MetLife 상승확률 : 99.75%, MetLife 상승여부 : 상승
Mettler Toledo 상승확률 : 99.80%, Mettler Toledo 상승여부 : 상승
MGM Resorts 상승확률 : 99.90%, MGM Resorts 상승여부 : 상승
Microchip Technology 상승확률 : 99.97%, Microchip Technology 상승여부 : 상승
Micron Technology 상승확률 : 99.99%, Micron Technology 상승여부 : 상승
Microsoft 상승확률 : 52.99%, Microsoft 상승여부 : 상승
Mid-America Apartment Communities 상승확률 : 0.00%, Mid-America Apartment Communities 상승여부 : 하락
Moderna 상승확률 : 15.68%, Moderna 상승여부 : 하락
Mohawk Industries 상승확률 : 98.67%, Mohawk Industries 상승여부 : 상승
Molina Healthcare 상승확률 : 27.05%, Molina Healthcare 상승여부 : 하락
Molson Coors Beverage Company 상승확률 : 65.43%, Molson Coors Beverage Company 상승여부 : 상승
Mondelez International 상승확률 : 0.08%, Mondelez International 상승여부 : 하락
Monolithic Power Systems 상승확률 : 98.08%, Monolithic Power Systems 상승여부 : 상승
Monster Beverage 상승확률 : 55.94%, Monster Beverage 상승여부 : 상승
Moody's Corporation 상승확률 : 78.58%, Moody's Corporation 상승여부 : 상승
Morgan Stanley 상승확률 : 99.98%, Morgan Stanley 상승여부 : 상승
Mosaic Company (The) 상승확률 : 29.09%, Mosaic Company (The) 상승여부 : 하락
Motorola Solutions 상승확률 : 2.54%, Motorola Solutions 상승여부 : 하락
MSCI Inc- 상승확률 : 19.33%, MSCI Inc- 상승여부 : 하락
Nasdaq, Inc- 상승확률 : 8.08%, Nasdaq, Inc- 상승여부 : 하락
NetApp 상승확률 : 99.99%, NetApp 상승여부 : 상승
Netflix 상승확률 : 46.61%, Netflix 상승여부 : 하락
Newmont 상승확률 : 91.53%, Newmont 상승여부 : 상승
News Corp (Class A) 상승확률 : 1.88%, News Corp (Class A) 상승여부 : 하락
News Corp (Class B) 상승확률 : 26.30%, News Corp (Class B) 상승여부 : 하락
NextEra Energy 상승확률 : 91.53%, NextEra Energy 상승여부 : 상승
Nike, Inc- 상승확률 : 99.58%, Nike, Inc- 상승여부 : 상승
NiSource 상승확률 : 0.05%, NiSource 상승여부 : 하락
Nordson Corporation 상승확률 : 18.69%, Nordson Corporation 상승여부 : 하락
Norfolk Southern 상승확률 : 97.85%, Norfolk Southern 상승여부 : 상승
Northern Trust 상승확률 : 99.11%, Northern Trust 상승여부 : 상승
Northrop Grumman 상승확률 : 14.31%, Northrop Grumman 상승여부 : 하락
Norwegian Cruise Line Holdings 상승확률 : 85.45%, Norwegian Cruise Line Holdings 상승여부 : 상승
NRG Energy 상승확률 : 99.39%, NRG Energy 상승여부 : 상승
Nucor 상승확률 : 99.95%, Nucor 상승여부 : 상승
Nvidia 상승확률 : 99.51%, Nvidia 상승여부 : 상승
NVR, Inc- 상승확률 : 98.13%, NVR, Inc- 상승여부 : 상승
NXP Semiconductors 상승확률 : 99.87%, NXP Semiconductors 상승여부 : 상승
O’Reilly Automotive 상승확률 : 33.00%, O’Reilly Automotive 상승여부 : 하락
Occidental Petroleum 상승확률 : 98.25%, Occidental Petroleum 상승여부 : 상승
Old Dominion 상승확률 : 99.23%, Old Dominion 상승여부 : 상승
Omnicom Group 상승확률 : 99.97%, Omnicom Group 상승여부 : 상승
ON Semiconductor 상승확률 : 100.00%, ON Semiconductor 상승여부 : 상승
Oneok 상승확률 : 69.54%, Oneok 상승여부 : 상승
Oracle Corporation 상승확률 : 99.78%, Oracle Corporation 상승여부 : 상승
Otis Worldwide 상승확률 : 99.82%, Otis Worldwide 상승여부 : 상승
Paccar 상승확률 : 99.61%, Paccar 상승여부 : 상승
Packaging Corporation of America 상승확률 : 86.53%, Packaging Corporation of America 상승여부 : 상승
Palantir Technologies 상승확률 : 25.16%, Palantir Technologies 상승여부 : 하락
Palo Alto Networks 상승확률 : 99.93%, Palo Alto Networks 상승여부 : 상승
Paramount Global 상승확률 : 93.16%, Paramount Global 상승여부 : 상승
Parker Hannifin 상승확률 : 95.28%, Parker Hannifin 상승여부 : 상승

In [6]:
import pandas as pd

results = []

for i, ticker in enumerate(ticker_Group):
    kor_name = ticker_names.get(ticker, ticker)
    pred = y_pred[i]
    prob = y_proba[i][1] * 100
    results.append({
        "Ticker": ticker,
        "종목": kor_name,
        "상승확률": round(prob, 2),
        "상승여부": "상승" if prob > 50 else "하락"
    })

df_result = pd.DataFrame(results)
df_result = df_result.iloc[:,1:4]
df_result

                      종목       상승확률 상승여부
0                     3M  99.830002   상승
1            A- O- Smith  99.839996   상승
2    Abbott Laboratories  63.400002   상승
3                 AbbVie   0.360000   하락
4              Accenture   1.000000   하락
..                   ...        ...  ...
498           Xylem Inc-  99.239998   상승
499          Yum! Brands   7.410000   하락
500   Zebra Technologies  99.980003   상승
501        Zimmer Biomet  98.430000   상승
502               Zoetis   4.870000   하락

[503 rows x 3 columns]

In [7]:
import os
save_path = f"/Users/kjb/Desktop/hateslop/프로젝트/예측데이터/({today})예측.csv"
df_result.to_csv(save_path, index=False)

In [8]:
df_result["상승여부"].value_counts()

상승여부
상승    350
하락    153
Name: count, dtype: int64